public class IntegeratingTwoSalesforceOrgHandler {

    //Write below clientId, clientSecret, username, password from Org B Destination Org)

 private final String clientId ='3MVG9t0sl2P.pByqLoOEDjuIwsyPNkD5jVJQt4UM4LKZ4Z2qATt4k1CvYsgp7g_8cQzB5NuNJ0racqMVJBvMy';

    private final String clientSecret ='4B8E794A2E65086ADF56BD95409B9CA1D12A6A399F97E673215CCD5009C3E963';

    private final String username = 'anna.stachelek1@britenet.com.pl';

    private final String password = 'Wiatrak.04';

    public class resWrapper

    {

        public String id;

        public String access_token;

    }

    public class accountWrap{

        public string case_region;

        public String wName;

        public String wPhone;

        public accountWrap(String name,String phone)

        {

            this.wName =name;

            this.wPhone =phone;

        } 

    }
}